### PR TITLE
Feat: <Modal> now behaves like bootstrap's .modal

### PR DESCRIPTION
**Pull request by michaelkrukov**
- Added `ModalBackdrop`.
- Renamed `Modal` to `ModalWrapper`.
- Added `Modal`.
- Now only one `Modal` is needed for use.
- Added `returnFocusAfterClose` prop for returning focus to element that triggered modal opening.
- Added `backdrop` prop for hiding backdrop or making it static (clicks is ignored).
- Updated tests and snapshots.
- Updated storybook.

[Codesandbox with new `Modal`](https://codesandbox.io/s/1vj4n0nqw7?fontsize=14)

Solves #35

### CODE REVIEW

**Comment by aichbauer** [comment]
@michaelkrukov the code looks very clean, and I like the tests and the new functionality.

Some points that we need before we can merge it:

* the `README.md` of the modal component also needs an update.
* the animation in the codesandbox is seamlessly and works good, but when I start the storybook and check out the fades of the modals they are a bit off, maybe we need to tweak some settiings on the fading animation. Do you have any idea?

**Comment by michaelkrukov** [comment]
@aichbauer what exactly wrong with fading? I don't see the difference between codesandbox's modal and one in the storybook. Is this problem consistent?

**Comment by aichbauer** [comment]
@michaelkrukov here are two gifs. as you can see the animation in the storybook is lagging and the version on codesandbox is really smooth...

this is how the animation is in the storybook example, I dont know why?
ezgif com-video-to-gif

This is the animation on code sandbox... is there something different?
ezgif com-video-to-gif (1)

**Comment by michaelkrukov** [comment]
@aichbauer no, the code inside of the codesandbox and inside of the storybook is the same. 

I have no problems with the Modal in the storybook in: `Mozilla Firefox 66.0.3`, `Google Chrome 74.0.3729.131 ` and `Opera 60.0.3255.70`. Storybook version: `5.0.10`.

**Comment by aichbauer** [comment]
@michaelkrukov i'll need to check my versions, but i think maybe it has something to do with storybook development build. I will create a production build and test it against the same versions that you are using... I will try to make this as soon as possible...

**Comment by aichbauer** [comment]
@michaelkrukov tested it, and it seems to be a performance issue with chrome on `v73.0.3683.103`

**Pull request merged**
