### PR TITLE
Feat: props for passing props to modal components

### LINKED ISSUE #41: Fix: passing props to modal
Currently in `v4.0.0-alpha.0` it is not possible to add additional props to the Modal eg. `className`, `style`... this should be possible, to offer the highest flexibility to generate your own library... This is also necessary to use this component with also we should have a way to add a `style` and `className` prop to the fade component, and to modal backdrop component, modal content component... and so on... e.g. something like `fadeStyle`, `fadeClassName`, `modalBackdropStyle`, `modalBackdropClassName`...

https://github.com/aichbauer/styled-bootstrap-components/blob/f69064d4feaec8ed5300ec71d3b2e681dce7bc20/packages/styled-modal-component/src/components/Modal.js#L133

https://github.com/aichbauer/styled-bootstrap-components/blob/f69064d4feaec8ed5300ec71d3b2e681dce7bc20/packages/styled-modal-component/src/components/Modal.js#L134

https://github.com/aichbauer/styled-bootstrap-components/blob/f69064d4feaec8ed5300ec71d3b2e681dce7bc20/packages/styled-modal-component/src/components/Modal.js#L140

https://github.com/aichbauer/styled-bootstrap-components/blob/f69064d4feaec8ed5300ec71d3b2e681dce7bc20/packages/styled-modal-component/src/components/Modal.js#L147

https://github.com/aichbauer/styled-bootstrap-components/blob/f69064d4feaec8ed5300ec71d3b2e681dce7bc20/packages/styled-modal-component/src/components/Modal.js#L151

### PR DESCRIPTION
**Pull request by michaelkrukov**
- Added `fadeProps`, `wrapperProps`, `dialogProps`, `contentProps`, `backdropProps`
- Updated storybook with an example
- Updated README.md

This way users can pass refs, styles, class names, e.t.c. I think that's a nice solution.

closes #41

### CODE REVIEW

**Comment by aichbauer** [comment]
@michaelkrukov to use this component with styled-components e.g. 

```jsx
const myModal = styled(Modal)`
  /*some styles*/
`;
```

the modal has to accept the a `className` prop at the top level element or am I wrong?

```jsx
<Fade
  {...this.props}
  // or
  {...this.props.className}
>
```

**Comment by michaelkrukov** [comment]
@aichbauer Yeah, I suppose, in order to `styled(Modal)` to work component should pass className to Fade. But it's pretty questionable as `Modal` itself is a combination of other components that use absolute and fixed positioning and pretty independent from each other. It doesn't look like a use case for styled-components. In my opinion for customization, it's better to leave the ability to pass `className` or `style` to specific parts of `Modal`

**Comment by michaelkrukov** [comment]
I'm gonna check this and commit if everything is right.

```js
render() {
    const {
      fadeProps,
      wrapperProps,
      dialogProps,
      contentProps,
      backdropProps,
      centered,
      noRadius,
      children,
      backdrop,
      sm,
      lg,
      ...rest
    } = this.props;

    const { hidden } = this.state;

    return (
      <Fade
        hidden={hidden}
        ref={this.refFade}
        {...fadeProps}
        {...rest}
      >
```

**Comment by michaelkrukov** [comment]
Still, I don't recommend using `styled(Modal)` for customization as this will only affect the `Fade` component and hide that fact unline passing `fadeProps`

**Comment by aichbauer** [comment]
@michaelkrukov  I totally agree with you, but I think this should be possible because when using style props you are not able to style some things like `pseudo-classes` or `media-queries`... and with the className you are forced to use a separate css again. And we want the user to deside wether they use `css, css-in-js, or the style prop` that is what we propagate in our readme...

**Pull request merged**
