### PR TITLE
adds padding to container and negative margin to rows to align with BS 4 grid

### PR DESCRIPTION
**Pull request by apisandipas**
The Bootstrap grid has a quirky feature of having negative margins on rows. This is because theres ideally 1 container and any number of infinitely nested Rows and Columns. The negative margin on Rows enables this nesting capability and is missing from your implementation, which I quite otherwise like. Hope you will consider this PR and happy coding.

### CODE REVIEW

**Comment by aichbauer** [comment]
@apisandipas thanks for contributing

I will take a look at this PR as soon as possible.

**Comment by michaelkrukov** [comment]
@apisandipas, hey, I think you should update snapshots and follow this project's code style (Airbnb) to better fit your changes into the repo :+1:

**Comment by aichbauer** [comment]
@apisandipas If you consider the changes @michaelkrukov proposed we could definitely consider this feature/fix.

**Comment by apisandipas** [comment]
Updated to removed my 'prettier' formatting, sorry about that. Now you can see, it's a really simple change.

**Comment by apisandipas** [comment]
Okay, I've updated the snapshots as requested now too.

**Pull request closed without merging**
